# Generated by Django 4.2.7 on 2023-11-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='accountno',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='ifsccode',
            new_name='ifsc',
        ),
        migrations.AlterField(
            model_name='bank',
            name='amount',
            field=models.FloatField(),
        ),
    ]
