# Generated by Django 4.2.7 on 2023-11-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='account',
            new_name='accountno',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='ifsc',
            new_name='ifsccode',
        ),
        migrations.AlterField(
            model_name='bank',
            name='amount',
            field=models.FloatField(max_length=100),
        ),
    ]
